all:	ca ca_ieee ca1

ca:	ca.c
	gcc -std=c99 ca.c -o ca -I ${HOME}/primesieve-5.4.2/include/ -I /data/local/include -L ${HOME}/primesieve-5.4.2/.libs -L /data/local/lib -larb -lprimesieve

ca1:	ca1.c pari.c
	gcc -O3 -std=c99 ca1.c -o ca1 -I ${HOME}/primesieve-5.4.2/include/ -I /data/local/include -L ${HOME}/primesieve-5.4.2/.libs -L /data/local/lib -larb -lprimesieve -lpari

ca_ieee: ca_ieee.cpp
	g++ ca_ieee.cpp -o ca_ieee -O1 -frounding-math -fomit-frame-pointer -finline-functions -mfpmath=387 -I ${HOME}/primesieve-5.4.2/include/ -I ~/crlibm/ -L ${HOME}/primesieve-5.4.2/.libs  -L ~/crlibm/ -lprimesieve -lcrlibm -lm
