
# This file was *autogenerated* from the file matteo_table.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_2000 = Integer(2000); _sage_const_1p574en11 = RealNumber('1.574e-11'); _sage_const_5 = Integer(5); _sage_const_1500 = Integer(1500); _sage_const_9 = Integer(9); _sage_const_2445999556030 = Integer(2445999556030); _sage_const_4p209en13 = RealNumber('4.209e-13'); _sage_const_25 = Integer(25); _sage_const_1012519281279 = Integer(1012519281279); _sage_const_8p852en12 = RealNumber('8.852e-12'); _sage_const_1019509030546 = Integer(1019509030546); _sage_const_3000 = Integer(3000); _sage_const_0p97 = RealNumber('0.97'); _sage_const_0p98 = RealNumber('0.98'); _sage_const_1000 = Integer(1000); _sage_const_2445999556029 = Integer(2445999556029); _sage_const_1364832983117 = Integer(1364832983117); _sage_const_3p381en12 = RealNumber('3.381e-12'); _sage_const_3501 = Integer(3501); _sage_const_2500 = Integer(2500); _sage_const_1p193en12 = RealNumber('1.193e-12')
def matteo_table():
    o = open("epsilon_table.txt", "a")
    o.write("Values of epsilon, 1000 < log(x) < 3500, quick and dirty version. \r\n\r\n")
    s = _sage_const_0p97 
    d = _sage_const_1p574en11 
    m = _sage_const_9 
    T = _sage_const_1012519281279 
    for b in range (_sage_const_1000 ,_sage_const_1500 ,_sage_const_5 ):
        o.write("For b = {}, epsilon = {}. \r\n".format(b, eps(b, m, s, d, T).n()))
        print "{}% finished.".format(((b - _sage_const_1000 )/_sage_const_25 ).n())
    #quick end
    o.close
    return "done!"
    s = _sage_const_0p98 
    d = _sage_const_8p852en12 
    T = _sage_const_1019509030546 
    m = _sage_const_5 
    for b in range (_sage_const_1500 ,_sage_const_2000 ,_sage_const_5 ):
        o.write("For b = {}, epsilon = {}. \r\n".format(b, eps(b, m, s, d, T).n()))
        print "{}% finished.".format(((b - _sage_const_1000 )/_sage_const_25 ).n())
    m = _sage_const_2 
    d = _sage_const_3p381en12 
    T = _sage_const_1364832983117 
    for b in range (_sage_const_2000 ,_sage_const_2500 ,_sage_const_5 ):
        o.write("For b = {}, epsilon = {}. \r\n".format(b, eps(b, m, s, d, T).n()))
        print "{}% finished.".format(((b - _sage_const_1000 )/_sage_const_25 ).n())
    d = _sage_const_1p193en12 
    T = _sage_const_2445999556029 
    for b in range (_sage_const_2500 ,_sage_const_3000 ,_sage_const_5 ):
        o.write("For b = {}, epsilon = {}. \r\n".format(b, eps(b, m, s, d, T).n()))
        print "{}% finished.".format(((b - _sage_const_1000 )/_sage_const_25 ).n())
    d = _sage_const_4p209en13 
    T = _sage_const_2445999556030 
    for b in range (_sage_const_3000 ,_sage_const_3501 ,_sage_const_5 ):
        o.write("For b = {}, epsilon = {}. \r\n".format(b, eps(b, m, s, d, T).n()))
        print "{}% finished.".format(((b - _sage_const_1000 )/_sage_const_25 ).n())
    o.close

