g_sum:	g_sum.cpp
	g++ -finline-functions -fomit-frame-pointer -frounding-math -mfpmath=387 -o g_sum g_sum.cpp -lcrlibm

g_sum1:	g_sum1.cpp
	g++ -finline-functions -fomit-frame-pointer -frounding-math -mfpmath=387 -o g_sum1 g_sum1.cpp -lcrlibm

A_T:	A_T.cpp
	g++ -finline-functions -fomit-frame-pointer -frounding-math -mfpmath=387 -o A_T A_T.cpp -lcrlibm


first_N:	first_N.cpp
	g++ -finline-functions -fomit-frame-pointer -frounding-math -mfpmath=387 -o first_N first_N.cpp -lcrlibm
