all: crocker3 crocker4

crocker3: crocker_threads_nc_3.cpp
	g++ -O3 -o crocker_threads_nc_3 crocker_threads_nc_3.cpp -lpthread

crocker4: crocker_threads_nc_4.cpp
	g++ -O3 -o crocker_threads_nc_4 crocker_threads_nc_4.cpp -lpthread
